### ISSUE TITLE
ANR stack trace

### ISSUE THREAD

**Issue by dappledore** [robotmedia/AndroidBillingLibrary#33]
Some times i get a force close with the stack trace below, then waiting a short while the error goes away.Any ideas?

java.lang.RuntimeException: Unable to start service net.robotmedia.billing.BillingService@46265ad8 with Intent { act=com.123.REQUEST_PURCHASE cmp=com.123/net.robotmedia.billing.BillingService (has extras) }: java.lang.NullPointerException
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3282)
at android.app.ActivityThread.access$3600(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2211)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:144)
at android.app.ActivityThread.main(ActivityThread.java:4937)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at android.os.Parcel.readException(Parcel.java:1253)
at android.os.Parcel.readException(Parcel.java:1235)
at com.android.vending.billing.IMarketBillingService$Stub$Proxy.sendBillingRequest(IMarketBillingService.java:100)
at net.robotmedia.billing.request.BillingRequest.run(BillingRequest.java:79)
at net.robotmedia.billing.BillingService.runRequest(BillingService.java:224)
at net.robotmedia.billing.BillingService.runRequestOrQueue(BillingService.java:238)
at net.robotmedia.billing.BillingService.requestPurchase(BillingService.java:201)
at net.robotmedia.billing.BillingService.handleCommand(BillingService.java:183)
at net.robotmedia.billing.BillingService.onStartCommand(BillingService.java:169)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3267)
... 10 more/

**Comment by dappledore** [comment]
I just read the other post, i also just reset my phone , so i guess its related to not setting up the market before doing a purchase, I guess i should close this thread, since its duplicated?

**Comment by dappledore** [comment]
I should also add that onBillingChecked returned true.

**Comment by ophidian** [comment]
Actually, this issue is mentioned here:

http://code.google.com/p/marketbilling/issues/detail?id=25

Quote:

This happens when the device has not accepted the License Agreement and try to call this line I encountered this problem when my client just bought a new device and try run my app which make use of inApp so he didnt ever opened market app in his device and so had never accepted the Agreement once you accept the it this error will not be there

**Comment by ophidian** [comment]
I'm getting this reported quite a few times. I would believe that it's more than just the above. Or maybe we should handle the bug more gracefully? I'm not sure if this is already fixed in another branch?

**Comment by dappledore** [comment]
Yes im also still getting this reported a few times a day recently, I dont think its just related to accepting the License Agreement, it seems to occur too often.
